# Default initial positions for my_dual_robot_cell's ros2_control fake system

initial_positions:
  robot2_elbow_joint: 0
  robot2_shoulder_lift_joint: 0
  robot2_shoulder_pan_joint: 0
  robot2_wrist_1_joint: 0
  robot2_wrist_2_joint: 0
  robot2_wrist_3_joint: 0
  robot1_elbow_joint: 0
  robot1_shoulder_lift_joint: 0
  robot1_shoulder_pan_joint: 0
  robot1_wrist_1_joint: 0
  robot1_wrist_2_joint: 0
  robot1_wrist_3_joint: 0