---
name: pre-commit
on:
  pull_request:
jobs:
  pre-commits:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: "Install dependencies"
        run: |
          python -m pip install catkin_lint
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files --hook-stage manual
