name: Rolling Binary Testing
on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '12 34 * * *'

jobs:
  rolling_binary_testing:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: rolling
      ros_repo: testing
      ref_for_scheduled_build: main
